#!/usr/bin/env bash
set -euo pipefail

# Generated by fallow setup-hooks.
# Installer version: 3.9.1
# Requires bash and jq. On Windows run via git-bash or WSL.
# Blocks Claude Code git commit and git push when fallow audit returns verdict fail.
#
# Local modifications to the generated 3.9.1 script (all tighten the gate):
#  - the git matcher skips leading global options and treats quotes as delimiters,
#    so `git -C dir commit`, `git -c k=v commit` and `bash -c "git commit"` are gated
#  - a missing jq or fallow binary blocks instead of skipping: that is a persistent
#    misconfiguration, not a transient failure, and it would silence the gate forever
#  - --version output is truncated to its first line before the floor comparison
# Audit runtime errors still fail open with a single stderr notice so transient
# breakage does not wedge every commit; only the missing-prerequisite paths block.
#
# Version floor (FALLOW_GATE_MIN_VERSION, default 2.85.0). The gate passes
# --gate-marker agent (added in v2.85.0) so Impact can record containment;
# older binaries reject the flag entirely, which would make every audit fail
# open. The floor also covers the older uncommitted-changes inclusion fix
# (aabb8e1b, v2.46.0). Set the env var to the empty string to disable.
# Floor comparison uses `sort -V`; GNU and BSD agree on plain semver but
# diverge on prereleases (BSD sorts `2.48.0-alpha.1` ABOVE `2.48.0`, GNU below).
# If you set a prerelease floor explicitly, verify the behavior on the target OS.

INPUT="$(cat)"

# jq reads the command out of the hook payload and parses the audit result below.
# Without it, fall back to scanning the raw payload: that is enough to tell a gated
# git call apart from every other Bash command, so unrelated commands keep flowing
# and only the gated ones stop at the hard block further down.
if command -v jq >/dev/null 2>&1; then
  CMD="$(jq -r '.tool_input.command // empty' <<<"$INPUT")"
  HAVE_JQ=1
else
  CMD="$INPUT"
  HAVE_JQ=0
fi

# Global options may sit between `git` and the subcommand (`git -C dir commit`,
# `git -c user.name=x commit`, `git --no-pager push`), so step over any run of
# leading flags -- including the detached value that -c and -C take. Quotes count
# as delimiters on both ends so `bash -c "git commit"` and the raw JSON payload of
# the jq fallback are matched too.
GIT_GATED_RE=$'(^|[[:space:];|&()"\'])git([[:space:]]+(-[cC][[:space:]]+[^[:space:]]+|--[^[:space:]]+|-[a-zA-Z]+))*[[:space:]]+(commit|push)([[:space:]"\']|$)'

if ! printf '%s\n' "$CMD" | grep -Eq "$GIT_GATED_RE"; then
  exit 0
fi

if [ "$HAVE_JQ" -eq 0 ]; then
  {
    echo "fallow-gate: blocked: jq not on PATH, so the audit cannot run."
    echo "fallow-gate: install jq (e.g. brew install jq) to restore the gate."
  } >&2
  exit 2
fi

if command -v fallow >/dev/null 2>&1; then
  RUNNER=(fallow)
  BIN_DESC="$(command -v fallow)"
elif command -v npx >/dev/null 2>&1 && VER_PROBE="$(npx --no-install fallow --version 2>/dev/null | head -n1 || true)" && [[ "$VER_PROBE" == fallow* ]]; then
  RUNNER=(npx --no-install fallow)
  BIN_DESC="npx --no-install fallow"
else
  {
    echo "fallow-gate: blocked: fallow binary not found (tried PATH and npx --no-install)."
    echo "fallow-gate: run \`bun install\` to restore the local devDependency, or install it"
    echo "fallow-gate: globally (npm install -g fallow@latest)."
  } >&2
  exit 2
fi

# --version prints a signature-verification line after the version itself, so keep
# only the first line; otherwise VERSION carries a newline into the floor compare.
VERSION_RAW="$("${RUNNER[@]}" --version 2>/dev/null | head -n1 || true)"
VERSION="${VERSION_RAW#fallow }"
VERSION="${VERSION%% *}"

MIN_VERSION="${FALLOW_GATE_MIN_VERSION-2.85.0}"
if [ -n "$MIN_VERSION" ] && [ -n "$VERSION" ]; then
  LOWER="$(printf '%s\n%s\n' "$MIN_VERSION" "$VERSION" | sort -V | head -n1)"
  if [ "$LOWER" != "$MIN_VERSION" ]; then
    {
      echo "fallow-gate: blocked: $BIN_DESC is fallow $VERSION, below required $MIN_VERSION."
      echo "fallow-gate: older binaries reject the --gate-marker flag this gate passes"
      echo "fallow-gate: (added in fallow v2.85.0), so the audit cannot run."
      echo "fallow-gate: upgrade the fallow on PATH (e.g. npm install -g fallow@latest or"
      echo "fallow-gate: cargo install fallow-cli), or set FALLOW_GATE_MIN_VERSION= to disable."
    } >&2
    exit 2
  fi
fi

TMP_JSON="$(mktemp)"
TMP_ERR="$(mktemp)"
cleanup() {
  rm -f "$TMP_JSON" "$TMP_ERR"
}
trap cleanup EXIT

if "${RUNNER[@]}" audit --format json --quiet --explain --gate-marker agent >"$TMP_JSON" 2>"$TMP_ERR"; then
  STATUS=0
else
  STATUS=$?
fi

VERDICT="$(jq -r '.verdict // empty' <"$TMP_JSON" 2>/dev/null || true)"
IS_ERROR="$(jq -r '.error // false' <"$TMP_JSON" 2>/dev/null || echo false)"

if [ "$VERDICT" = "fail" ]; then
  echo "fallow-gate: blocked by fallow ${VERSION:-unknown} at $BIN_DESC" >&2
  cat "$TMP_JSON" >&2
  exit 2
fi

if [ "$STATUS" -eq 2 ] || [ "$IS_ERROR" = "true" ]; then
  MSG="$(jq -r '.message // empty' <"$TMP_JSON" 2>/dev/null || true)"
  if [ -n "$MSG" ]; then
    echo "fallow-gate: fallow audit runtime error ($MSG), skipping." >&2
  else
    echo "fallow-gate: fallow audit runtime error, skipping." >&2
  fi
  exit 0
fi

if [ "$STATUS" -ne 0 ]; then
  ERR_LINE="$(sed -n '1p' "$TMP_ERR" 2>/dev/null || true)"
  if [ -n "$ERR_LINE" ]; then
    echo "fallow-gate: fallow audit exited $STATUS ($ERR_LINE), skipping." >&2
  else
    echo "fallow-gate: fallow audit exited $STATUS, skipping." >&2
  fi
  exit 0
fi

exit 0
